### ISSUE TITLE
文章实验数据真实性有待考究

### ISSUE THREAD

**Issue by zhaojinbiao** [qinhongda8/R-YOLO#7]
## Additional context
![image](https://github.com/qinhongda8/R-YOLO/assets/81424671/ea8a6ea2-a076-4194-8166-f593a245873a)
讨论的数据根本就对不上！！！

**Comment by qinhongda8** [comment]
> ## ❔Question
> ## Additional context
> ![image](https://private-user-images.githubusercontent.com/81424671/293570317-ea8a6ea2-a076-4194-8166-f593a245873a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDI4NzksIm5iZiI6MTcwNDQ0MjU3OSwicGF0aCI6Ii84MTQyNDY3MS8yOTM1NzAzMTctZWE4YTZlYTItYTA3Ni00MTk0LTgxNjYtZjU5M2EyNDU4NzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA4MTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2OWM4ZDQxM2M1MWNmNTBkYmYzMjA5OWRiMDRlN2NmYjM3NzE5YzcxNjA0NTgwNmI1MjU0ZDZiNDUzZWYxOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-5ve8IkqbLGhU9f89-PHQDaIoAwB0gmcT6Eh1DLqU-U) 讨论的数据根本就对不上！！！

(39.6-34.1)/34.1=0.161=16.1%, (51.3-34.1)/34.1=0.504=50.4%, (55.8-34.1)/34.1=0.636=63.6%, (43.6-36.4)/36.4=0.197=19.7%, (51.3-41.2)/41.2=0.245=24.5%, (67.0-49.3)/49.3=0.359=35.9%, (55.8-45.6)/45.6=0.223=22.3%
